<!DOCTYPE html>
<html>
<head>
    <title>Vehicle Usage Report #{{ $report->id }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { text-align: center; color: #1e40af; }
        h2 { color: #1f2937; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f3f4f6; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { background-color: #f9fafb; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .good { color: #166534; }
    </style>
</head>
<body>

    <div class="header">
        <h1>SriTravel - Vehicle Usage Report</h1>
        <p>Period: {{ $report->start_date }} - {{ $report->end_date }}</p>
        <p>Generated on: {{ now()->format('M d, Y h:i A') }}</p>
    </div>

    @if(!empty($reportData['type_usage']))
    <div class="summary">
        <h2>Vehicle Type Summary</h2>
        <table>
            <thead>
                <tr>
                    <th>Vehicle Type</th>
                    <th>Total Bookings</th>
                    <th>Total Days Rented</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportData['type_usage'] as $type)
                <tr>
                    <td><strong>{{ $type['type'] }}</strong></td>
                    <td>{{ $type['total_bookings'] }}</td>
                    <td>{{ $type['total_days_rented'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <h2>Vehicle Wise Usage Details</h2>
    <table>
        <thead>
            <tr>
                <th>Vehicle</th>
                <th>Registration</th>
                <th>Type</th>
                <th>Bookings</th>
                <th>Days Rented</th>
                <th>Utilization</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['vehicle_usage'] ?? [] as $item)
            <tr>
                <td>{{ $item['make'] }} {{ $item['model'] }}</td>
                <td>{{ $item['registration_number'] }}</td>
                <td>{{ ucfirst($item['type']) }}</td>
                <td>{{ $item['bookings_count'] }}</td>
                <td>{{ $item['days_rented'] }}</td>
                <td class="good">{{ $item['utilization'] }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <p style="text-align: center; margin-top: 30px; color: #6b7280;">
        Generated by SriTravel Admin Panel
    </p>

</body>
</html>